version: '2'

services:

  jenkins:
    #image: jenkins/jenkins:lts
    build: jenkins/
    volumes:
       - jenkins_data:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sonarnet
    ports:
      - '8080:8080'
      - '50000:50000'
    #group_add:
    #  - 998 # Docker group
    privileged: true
    user: root

  nexus:
    image: "sonatype/nexus3"
    ports:
      - "10680:8081"
      - "8084:8084"
    volumes:
      - "./nexus:/nexus-data"

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  jenkins_data:
  nexus: