FROM jenkins/jenkins:lts

USER root

RUN apt-get update
RUN apt-get install ca-certificates -y
RUN apt-get install curl -y
RUN apt-get install gnupg -y
RUN apt-get install lsb-release -y

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg


RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update

RUN apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y

# Error : The repository 'https://download.docker.com/linux/ubuntu bullseye Release' does not have a Release file.